name: fard
description: "Qada Tracker - Islamic missed prayer tracking app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  meta: ^1.11.0
  intl: ^0.19.0
  table_calendar: ^3.1.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  freezed: ^2.4.7
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
